#spring.application.name=meetcake-back
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meetcake_back
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver